dependencies:
- python=3.6.2
- numpy=1.12.1
- scikit-learn=0.19.1
- matplotlib=2.0.2
- seaborn=0.7.1
- click=6.7
- coverage
- flake8
- pip=9.0
- pip:
    - jupyter
    - pysal==1.14.2
    - s2sphere==0.2.4
